spring:
  application:
    name: kakaapibackend
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kaka?serverTimezone=UTC
    username: root
    password: Ybmq.785679
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # session 失效时间（分钟）
  session:
    timeout: 86400
  servlet:
    multipart:
      max-file-size: 3MB

server:
  port: 8081
  servlet:
    context-path: /api

#dubbo 配置
dubbo:
  application:
    name: kakaapibackend-backend
  protocol:
    name: dubbo
    port: -1
  registry:
    id:
    address: nacos://localhost:8848


# mybatis-plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
#图床配置
aliyun:
  oss:
    # oss对外服务的访问域名
    endpoint: oss-cn-beijing.aliyuncs.com
    # 访问身份验证中用到用户标识
    accessKeyId: LTAI5t85SfDtjtcot16eKvBX
    # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    accessKeySecret: s5C7B2q9A9xWQSn7AGu8WEwxlqXbqF
    # oss的存储空间
    bucketName: kaapi-avatar
    # 上传文件大小(M)
    maxSize: 3
    # 上传文件夹路径前缀
    dir:
      prefix: userAvatar/



